//
// Generated by JTB 1.3.2
//

import java.util.ArrayList;
import java.util.Enumeration;
import syntaxtree.AllocationExpression;
import syntaxtree.AndExpression;
import syntaxtree.ArrayAllocationExpression;
import syntaxtree.ArrayAssignmentStatement;
import syntaxtree.ArrayLength;
import syntaxtree.ArrayLookup;
import syntaxtree.ArrayType;
import syntaxtree.AssignmentStatement;
import syntaxtree.Block;
import syntaxtree.BooleanType;
import syntaxtree.BracketExpression;
import syntaxtree.ClassDeclaration;
import syntaxtree.ClassExtendsDeclaration;
import syntaxtree.CompareExpression;
import syntaxtree.Expression;
import syntaxtree.ExpressionList;
import syntaxtree.ExpressionRest;
import syntaxtree.FalseLiteral;
import syntaxtree.FormalParameter;
import syntaxtree.FormalParameterList;
import syntaxtree.FormalParameterRest;
import syntaxtree.Goal;
import syntaxtree.Identifier;
import syntaxtree.IfStatement;
import syntaxtree.IntegerLiteral;
import syntaxtree.IntegerType;
import syntaxtree.MainClass;
import syntaxtree.MessageSend;
import syntaxtree.MethodDeclaration;
import syntaxtree.MinusExpression;
import syntaxtree.Node;
import syntaxtree.NodeList;
import syntaxtree.NodeListOptional;
import syntaxtree.NodeOptional;
import syntaxtree.NodeSequence;
import syntaxtree.NodeToken;
import syntaxtree.NotExpression;
import syntaxtree.PlusExpression;
import syntaxtree.PrimaryExpression;
import syntaxtree.PrintStatement;
import syntaxtree.Statement;
import syntaxtree.ThisExpression;
import syntaxtree.TimesExpression;
import syntaxtree.TrueLiteral;
import syntaxtree.Type;
import syntaxtree.TypeDeclaration;
import syntaxtree.VarDeclaration;
import syntaxtree.WhileStatement;
import visitor.GJVisitor;

public class VaporVisitor implements GJVisitor<String,SymbolTable> {

   private int tempCount = 0;
   private int ifCount = 1;
   public boolean debug = false;

   private String getNewIfLabel() {
      return "if" + ifCount++;
   }


   private String getNewTempName() {
      return "t." + tempCount++;
   }

   private void print(Object a) {
      if (debug == true) {
         System.out.println(a.toString().replaceAll("\n",", "));
      }
   }
   private void print(int a) {
      if (debug == true) {
         System.out.println(a);
      }
   }

   public String getIndentedStatementList(String vars, String statements) {
      if (vars == null)
         vars = "";
      if (statements == null)
         statements = "";
      String[] varList = vars.split("\n");
      String[] statementList = statements.split("\n");
      String result = "";
      if (vars.length() > 0) {
         for (String var : varList) {
            result += "  " + var + '\n';
         }
      }
      if (statements.length() > 0) {
         for (String statement : statementList) {
            result += "  " + statement + '\n';
         }
      }
      return result;
   }

   /*
   Add, Sub, MulS
   Eq, Lt, LtS
   PrintIntS
   HeapAllocZ
   Error
    */

   public String[] ops = new String[] {"Add(", "Sub(", "MulS(", "Eq(", "Lt(", "LtS(", "PrintIntS(", "HealAllocZ(", "Error(","="};

   public String[] makeTempVarIfNeeded(String statement) {
      String[] result;

      String[] temp = statement.split("\n");
      if (temp.length > 1) {
         String lastStatement = temp[temp.length-1];
         for (String op : ops) {
            if (lastStatement.contains(op)) {
               String var = getNewTempName();
               temp[temp.length-1] = var + " = " + lastStatement;
               statement = "";
               for (int i=0; i<temp.length;i++) {
                  if (i + 1 == temp.length) {
                     statement+=temp[i];
                  }
                  else {
                     statement+=temp[i]+'\n';
                  }
               }
               result = new String[]{var, statement};
               return result;
            }
         }
      }

      else {

         for (String op : ops) {
            if (statement.contains(op + '(')) {
               String var = getNewTempName();

               result = new String[]{var, var + " = " + statement};
               return result;
            }
         }
      }
      return new String[] {statement};
   }

   public String[] stripReturnedExpression(String statement) {
      String[] result = new String[0];

      System.out.println(statement);

      if (statement.matches("\\d*"))
         return new String[]{statement};

      if (statement.contains(";")) {
         result = statement.split(";");
         return result;
      }

      String[] temp = statement.split("\n");
      if (temp.length > 1) {
         String newStatement = "";
         String var = "";
         for (int i=0; i<temp.length;i++) {
            if (i+1 == temp.length) {
               var = getNewTempName();
               newStatement+=var+" = "+temp[i];
            }
            else {
               newStatement+=temp[i]+'\n';
            }
            result = new String[]{var, newStatement};
         }
      }
      else {
         result = new String[]{statement};
      }
      return result;
   }

   public String visit(NodeToken n, SymbolTable argu) {
      String _ret=n.toString();
      return _ret;
   }

   public String visit(NodeList n, SymbolTable argu) {
      String _ret="";
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         _ret += e.nextElement().accept(this,argu)+'\n';
         _count++;
      }
      print("NodeList: "+_ret);
      return _ret;
   }

   public String visit(NodeListOptional n, SymbolTable argu) {
      if ( n.present() ) {
         String _ret="";
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            _ret += e.nextElement().accept(this,argu)+'\n';
            _count++;
         }
         //print("NodeListOptional: "+_ret);
         return _ret;
      }
      else
         return "";
   }

   public String visit(NodeOptional n, SymbolTable argu) {
      if ( n.present() ) {
         return n.node.accept(this, argu);
      }
      else
         return "";
   }

   public String visit(NodeSequence n, SymbolTable argu) {
      String _ret="";
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         _ret += e.nextElement().accept(this,argu)+'\n';
         _count++;
      }
      print("NodeSequence: "+_ret);
      return _ret;
   }


   /**
    * f0 -> MainClass()
    * f1 -> ( TypeDeclaration() )*
    * f2 -> <EOF>
    */
   public String visit(Goal n, SymbolTable argu) {
      String main = n.f0.accept(this, argu);
      String classes = n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      if (classes == null)
         classes = "";
      return main + classes;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> ( VarDeclaration() )*
    * f15 -> ( Statement() )*
    * f16 -> "}"
    * f17 -> "}"
    */
   public String visit(MainClass n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);

      argu.setCurrentBlock("Main");

      String vars = n.f14.accept(this, argu);
      String statements = n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      n.f17.accept(this, argu);
      argu.addStatement(statements);

      String result = getIndentedStatementList(vars, statements);


      return "func Main()\n"+result+'\n';
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public String visit(TypeDeclaration n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public String visit(ClassDeclaration n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      String id = n.f1.accept(this, argu);
      argu.setCurrentClass(id);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public String visit(ClassExtendsDeclaration n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f0.accept(this, argu);
      String id = n.f1.accept(this, argu);
      argu.setCurrentClass(id);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public String visit(VarDeclaration n, SymbolTable argu) {
      String _ret="";
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public String visit(MethodDeclaration n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String id = n.f2.accept(this, argu);
      this.tempCount=0;
      argu.setCurrentBlock(argu.currentClass+'.'+id);
      print(argu.currentBlock);
      n.f3.accept(this, argu);
      String params = n.f4.accept(this, argu);
      String[] paramList = params.split("\n");
      params = "this ";
      for (String arg : paramList) {
         params += arg+" ";
      }
      argu.setBlockArgs(params);

      print("Params: "+params);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      String vars = n.f7.accept(this, argu);
      String statements = n.f8.accept(this, argu);

      print("Statements: "+statements);

      if (statements!=null && statements.length() > 0)
         argu.addStatement(statements);

      //String result = getIndentedStatementList(vars, statements);

      n.f9.accept(this, argu);
      String returnVal = n.f10.accept(this, argu);
      if (returnVal != null && returnVal.length()> 0) {
         String returnVar = argu.lastTemp;
         if (returnVar.length()==0) {
            argu.addStatement("ret "+returnVal);
         }
         else {
            argu.addStatement(returnVal+"\n"+"ret "+returnVar);
         }
      }





      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public String visit(FormalParameterList n, SymbolTable argu) {
      String _ret=null;
      String param1 = n.f0.accept(this, argu);
      String param2 = n.f1.accept(this, argu);
      if (param2.length() > 0)
         param1 +="\n"+param2;
      return param1;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public String visit(FormalParameter n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      _ret = n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public String visit(FormalParameterRest n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      _ret = n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public String visit(Type n, SymbolTable argu) {
      String _ret=null;

      String subtype = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public String visit(ArrayType n, SymbolTable argu) {
      String _ret=(String)"Array";
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public String visit(BooleanType n, SymbolTable argu) {
      String _ret=(String)"Boolean";
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public String visit(IntegerType n, SymbolTable argu) {
      String _ret=(String)"Int";
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public String visit(Statement n, SymbolTable argu) {
      String _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public String visit(Block n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      _ret = n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      print("Block: "+_ret);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public String visit(AssignmentStatement n, SymbolTable argu) {
      String _ret = null;
      String id = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String expr = n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      print("Assign:" + expr);

      String var = argu.lastTemp;
      argu.lastTemp="";

      if (var.length() == 0) {

         String[] expressionList = expr.split("\n");
         if (expressionList.length == 1)
            return id + " = " + expr;
         else {
            _ret = "";
            for (int i = 0; i < expressionList.length - 1; i++) {
               _ret += expressionList[i] + '\n';
            }
            _ret += id + " = " + expressionList[expressionList.length - 1];
            return _ret;
         }
      }
      else {
         _ret = expr+"\n"+id+" = "+var;
         return _ret;
      }
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public String visit(ArrayAssignmentStatement n, SymbolTable argu) {
      String _ret=null;
      String id = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String index = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      String newVal = n.f5.accept(this, argu);
      n.f6.accept(this, argu);


      print("index: "+index);
      String formalIndex = "";
      try {
         int i = Integer.parseInt(index) * 4 + 4;
         formalIndex = ""+i;
      }
      catch (Exception e) {
         formalIndex = index;
      }

      String newExpr = "["+id+"+"+formalIndex+"] = "+newVal;
      return newExpr;
      //return "";
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public String visit(IfStatement n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      String condition = n.f2.accept(this, argu);
      String expressionVar = argu.lastTemp;

      argu.lastTemp="";

      n.f3.accept(this, argu);
      String trueDo = n.f4.accept(this, argu);

      n.f5.accept(this, argu);
      String elseDo = n.f6.accept(this, argu);

      String ifLabel = getNewIfLabel();

      String result;

      if (expressionVar.length()==0) {
         result = "if0 "+condition+" goto :"+ifLabel+"_else";
      }
      else {
         result = condition+'\n'+"if0 "+expressionVar+" goto :"+ifLabel+"_else";
      }

      String[] trueCommands = trueDo.split("\n");
      trueDo = "";
      for (String command : trueCommands) {
         trueDo += "  "+command+"\n";
      }

      result +="\n"+trueDo+"goto :"+ifLabel+"_end";
      result += '\n'+ifLabel+"_else:";

      String[] elseCommands = elseDo.split("\n");
      elseDo = "";
      for (String command : elseCommands) {
         elseDo += "  "+command+"\n";
      }


      result+='\n'+elseDo;
      result+=ifLabel+"_end:";



      return result;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public String visit(WhileStatement n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String condition = n.f2.accept(this, argu);
      String expressionVar = argu.lastTemp;

      argu.lastTemp="";

      n.f3.accept(this, argu);
      String trueDo = n.f4.accept(this, argu);

      String ifLabel = getNewIfLabel();

      String result = ifLabel+"_start:";

      if (expressionVar.length()==0) {
         result += "\nif0 "+condition+" goto :"+ifLabel+"_end";
      }
      else {
         result += "\n"+condition+'\n'+"if0 "+expressionVar+" goto :"+ifLabel+"_end";
      }
      print("whiletrue: "+trueDo);
      String[] trueCommands = trueDo.split("\n");
      trueDo = "";
      for (String command : trueCommands) {
         trueDo += "  "+command+"\n";
      }

      result +="\n"+trueDo+"  goto :"+ifLabel+"_start";

      result+="\n"+ifLabel+"_end:";

      return result;
   }

   /**
    * f0 -> "print"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public String visit(PrintStatement n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String expr = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      print("Print lasttemp:"+argu.lastTemp);
      String var = argu.lastTemp;
      argu.lastTemp = "";
      if (var.length() == 0) {
         String[] expressionList = expr.split("\n");
         if (expressionList.length == 1) {
            String[] exprList = makeTempVarIfNeeded(expr);
            if (exprList.length > 1) {
               _ret = exprList[1]+"\n"+exprList[0];
            }
            else {
               _ret = "PrintIntS(" + expr + ")";
            }
            return _ret;
         }
         else {
            _ret = "";
            for (int i=0;i<expressionList.length-1;i++) {
               _ret += expressionList[i]+'\n';
            }
            String newVar = getNewTempName();
            _ret += newVar+" = "+expressionList[expressionList.length-1];
            _ret += "\nPrintIntS(" + newVar+")";
            return _ret;
         }
      }

      else {
         _ret = expr+"\n"+"PrintIntS("+var+")";
      }
      print("Print: "+_ret);
      //argu.addStatement("PrintIntS("+expr+")");
      return _ret;
   }

   /**
    * f0 -> AndExpression()
    *       | CompareExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | PrimaryExpression()
    */
   public String visit(Expression n, SymbolTable argu) {
      String _ret=null;
      String expr = n.f0.accept(this, argu);


      /*
      String[] exprList = stripReturnedExpression(expr);
      if (exprList.length == 1) {
         _ret = expr;
         argu.lastTemp="";
      }
      else {
         argu.lastTemp = exprList[0];
         _ret = exprList[1];
      }*/
      _ret = expr;


      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public String visit(AndExpression n, SymbolTable argu) {
      String _ret=null;
      //TODO
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<"
    * f2 -> PrimaryExpression()
    */
   public String visit(CompareExpression n, SymbolTable argu) {
      String lhs = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String rhs = n.f2.accept(this, argu);

      String var = getNewTempName();

      argu.lastTemp = var;

      String _ret =var+" = LtS("+lhs+" "+rhs+")";

      return _ret;
   }

   public String doBinop(String expr1, String expr2, String op, String var1, String var2) {
      String before = "";


      print("binop: ["+expr1+"], ["+expr2+']');
      print("binVars: "+var1+", "+var2);

      boolean alreadyTemp = false;

      if (var1.length() > 0) {
         before += expr1;
         expr1 = var1;
         alreadyTemp = true;
      }
      else {
         String[] exprList1 = makeTempVarIfNeeded(expr1);
         if (exprList1.length > 1) {
            before += exprList1[1] + '\n';
            expr1 = exprList1[0];
         }
      }

      if (var2.length() > 0) {
         before += expr2;
         expr2 = var2;
         alreadyTemp = true;
      }
      else {
         String[] exprList2 = makeTempVarIfNeeded(expr2);
         if (exprList2.length > 1) {
            before += exprList2[1] + '\n';
            expr2 = exprList2[0];
         }
      }
      if (alreadyTemp) {
         print(op + ": [" + before + "] -> [" + op + "(" + expr1 + " " + expr2 + ")]");
         return before +"\n"+ op + "(" + expr1 + " " + expr2 + ")";
      }
      else {
         print(op + ": [" + before + "] -> [" + op + "(" + expr1 + " " + expr2 + ")]");
         return before + op + "(" + expr1 + " " + expr2 + ")";
      }
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public String visit(PlusExpression n, SymbolTable argu) {
      String _ret=null;
      String expr1 = n.f0.accept(this, argu);
      String var1 = argu.lastTemp;
      argu.lastTemp="";
      n.f1.accept(this, argu);
      String expr2 = n.f2.accept(this, argu);
      String var2 = argu.lastTemp;
      argu.lastTemp="";
      return doBinop(expr1,expr2,"Add", var1, var2);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public String visit(MinusExpression n, SymbolTable argu) {
      String _ret=null;
      String expr1 = n.f0.accept(this, argu);
      String var1 = argu.lastTemp;
      argu.lastTemp="";
      n.f1.accept(this, argu);
      String expr2 = n.f2.accept(this, argu);
      String var2 = argu.lastTemp;
      argu.lastTemp="";
      return doBinop(expr1,expr2,"Sub", var1, var2);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public String visit(TimesExpression n, SymbolTable argu) {
      String _ret=null;
      String expr1 = n.f0.accept(this, argu);
      String var1 = argu.lastTemp;
      argu.lastTemp="";
      n.f1.accept(this, argu);
      String expr2 = n.f2.accept(this, argu);
      String var2 = argu.lastTemp;
      argu.lastTemp="";
      return doBinop(expr1,expr2,"MulS", var1, var2);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public String visit(ArrayLookup n, SymbolTable argu) {
      String _ret=null;
      String expr = n.f0.accept(this, argu);
      String id = argu.lastTemp;
      argu.lastTemp="";
      n.f1.accept(this, argu);
      String index = n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      print("Lookup: "+id);
      print("index: "+index);
      String formalIndex = "";
      try {
         int i = Integer.parseInt(index) * 4 + 4;
         formalIndex = ""+i;
      }
      catch (Exception e) {
         formalIndex = index;
      }

      String var = getNewTempName();
      argu.lastTemp = var;

      if (id.length() == 0)
         _ret = var+" = ["+expr+"+"+formalIndex+"]";
      else {
         _ret = expr+"\n"+var+" = ["+id+"+"+formalIndex+"]";
      }


      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public String visit(ArrayLength n, SymbolTable argu) {
      String _ret=null;
      String id = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String var = getNewTempName();
      _ret = var+" = ["+id+"]";
      argu.lastTemp = var;
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public String visit(MessageSend n, SymbolTable argu) {
      String _ret=null;
      String caller = n.f0.accept(this, argu);
      String var = argu.lastTemp;
      argu.lastTemp="";
      n.f1.accept(this, argu);
      String funcName = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      String args = n.f4.accept(this, argu);
      n.f5.accept(this, argu);

      String before = "";

      print("RawArgs: "+args);
      if (args.contains(";")) {
         String[] argsBroken = args.split(";");
         before = argsBroken[0];
         args = argsBroken[1].trim();
      }

      print("Before: "+before);
      print("NewArgs: "+args);



      String callVar = getNewTempName();
      String newVar = getNewTempName();
      argu.lastTemp = newVar;
      int offset = argu.getMethodOffset(argu.currentClass,funcName);


      if (var.length() == 0) {
         if (caller.equals("this")) {
            print("This Call:"+funcName+"; "+args);
            //print("Call: "+var+", "+funcName+", ["+args+"]");
            args = "this "+args;
            String result = before+'\n'+callVar+" = ["+caller+"]"+"\n"+callVar+" = ["+callVar+"+"+offset+"]"+"\n"+newVar+" = call "+callVar+"("+args+")";
            return result;
         }
         else {
            print("ERROR: var of length 0 in MessageSend");
            return "";
         }
      }
      else {
         _ret = caller;

         print("Call: "+var+", "+funcName+", ["+args+"]");

         String result = before+'\n'+caller+"\n"+callVar+" = ["+var+"]"+"\n"+callVar+" = ["+callVar+"+"+offset+"]"+"\n"+newVar+" = call "+callVar+"("+var+" "+args+")";
         return result;
      }

   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public String visit(ExpressionList n, SymbolTable argu) {
      String _ret=null;
      String expr = n.f0.accept(this, argu);
      String var = argu.lastTemp;
      argu.lastTemp = "";
      String exprRest = n.f1.accept(this, argu);

      if (var.length() == 0) {
         if (expr.contains("(") || expr.contains("[")) {
            String newVar = getNewTempName();
            _ret = newVar+" = "+expr+";"+newVar;
         }
         else {
            _ret = expr;
         }
      }
      else {
         _ret = expr+";"+var;
      }

      if (exprRest != null && exprRest.length()>0)
         _ret += exprRest;

      String before = "";
      String fixedArgs = "";

      String[] argList = _ret.split("\\|");
      for (String arg:argList) {
         if (arg.contains(";")) {
            String[] splitArgs = arg.split(";");
            before += splitArgs[0] + "\n";
            //System.out.println("\""+splitArgs[1]+"\"");
            fixedArgs += splitArgs[1].replaceAll("\n","").replaceAll(",","") + " ";
         }
         else {
            fixedArgs += arg.replaceAll("\n","").replaceAll(",","") + " ";
         }
      }

      _ret = before+";"+fixedArgs;

      print("ExprList: "+_ret);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public String visit(ExpressionRest n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      String expr = n.f1.accept(this, argu);
      String var = argu.lastTemp;
      argu.lastTemp = "";
      if (var.length() == 0) {
         if (expr.contains("(") || expr.contains("[")) {
            String newVar = getNewTempName();
            _ret = "|"+newVar+" = "+expr+";"+newVar;
         }
         else {
            _ret = "|"+expr;
         }
      }
      else {
         _ret = "|"+expr+";"+var;
      }
      return "|"+expr;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public String visit(PrimaryExpression n, SymbolTable argu) {
      String _ret=null;
      String expr = n.f0.accept(this, argu);
      //print("Primary: "+expr);
      if (expr.contains("|")) {
         String[] complexAssignment = expr.split("\\|");
         if (complexAssignment[0].equals("Array")) {
            int i = Integer.parseInt(complexAssignment[1]);
            String var = getNewTempName();
            argu.lastTemp = var;
            _ret = var+" = "+complexAssignment[2]+"\n["+var+"] = "+i;
            return _ret;
         }
         else {
            String className = complexAssignment[1];
            int size = argu.classes.get(className).classSize;
            String var = getNewTempName();
            argu.lastTemp = var;
            String ifVal = "null_"+getNewIfLabel();
            _ret = var+" = HeapAllocZ("+size+")\n["+var+"] = :vmt_"+className+"\nif "+var+" goto :"+ifVal+"\n  Error(\"null pointer\")\n"+ifVal+":";
            return _ret;
         }
      }
      else {
         _ret = expr;
      }

      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public String visit(IntegerLiteral n, SymbolTable argu) {
      String _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public String visit(TrueLiteral n, SymbolTable argu) {
      n.f0.accept(this, argu);
      return "1";
   }

   /**
    * f0 -> "false"
    */
   public String visit(FalseLiteral n, SymbolTable argu) {
      String _ret = n.f0.accept(this, argu);
      return "0";
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public String visit(Identifier n, SymbolTable argu) {
      String _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "this"
    */
   public String visit(ThisExpression n, SymbolTable argu) {
      String _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public String visit(ArrayAllocationExpression n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String expr = n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      print("Alloc: "+expr);
      int i = Integer.parseInt(expr);
      //TODO: for all array ops support symbols
      return "Array|"+i+"|HeapAllocZ("+((i*4)+4)+")";
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public String visit(AllocationExpression n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      String id = n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return "Class|"+id;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public String visit(NotExpression n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      String expr = n.f1.accept(this, argu);

      String var = getNewTempName();

      if (argu.lastTemp.length() == 0) {
         _ret = var + " = Sub(1 " + expr + ")";
         argu.lastTemp=var;
      }
      else {
         String tempVar = argu.lastTemp;
         argu.lastTemp="";
         _ret = expr +'\n' + var + " = Sub(1 " + tempVar + ")";
         argu.lastTemp=var;
      }

      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public String visit(BracketExpression n, SymbolTable argu) {
      String _ret=null;
      n.f0.accept(this, argu);
      _ret = n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

}
